### PR TITLE
fixed your countdown

### PR DESCRIPTION
**Pull request by dhtdht020**
I didn't like your dark theme so I removed it and that cool image you have is too tiny is I made it ten times larger

### CODE REVIEW

**Comment by dhtdht020** [comment]
I got reports your flower was very scary so I replaced it

**Comment by Multimegamander** [comment]
It needs 2d girl

**Comment by dhtdht020** [comment]
I got reports you need 2d girl instead of the flower so I did so

**Comment by Frutre3** [comment]
Yeah, no. Enjoy your block, both of you.

_...Dirty weeb..._

**Comment by Frutre3** [comment]
https://www.youtube.com/watch?v=U-LmXvlr8i8

**Pull request closed without merging**
